# Site settings
title: CYBERSOCKS
country: Vietnam                                                      # custom data
description: "Cybersocks Regional Competition 2016"
url: "https://cybersocks.org/vietnam/"                                 # custom data
domain: "cybersocks.org"
university1: "Đại học Bách khoa Hà Nội"             # custom data
university2: "Học viện Công nghệ Bưu chính viễn thông"   # custom data
register: "http://goo.gl/forms/cn22tFvXeMYR6dLr1"                     # custom data

# Build settings
baseurl: /
markdown: kramdown
permalink: /:title

# Custom variables
version: "2.0"
kramdown:
  input: GFM

include:
  - _pages
